name: DVC Repro
on: [pull_request]
jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: iterative/setup-dvc@v1
    - run: dvc pull
    - run: dvc repro  # Future: Validates pipeline